<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CollegeAdmin.Domain\CollegeAdmin.Domain.csproj" />
    <ProjectReference Include="..\CollegeAdmin.Contracts\CollegeAdmin.Contracts.csproj" />
    <ProjectReference Include="..\CollegeAdmin.Application\CollegeAdmin.Application.csproj" />
    <ProjectReference Include="..\CollegeAdmin.Infrastructure\CollegeAdmin.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
